[package]
name = "pollinations-mcp"
version = "1.0.9"
edition = "2021"
publish = false

[lib]
path = "src/pollinations-mcp.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
schemars = "1.2"
zed_extension_api = "0.7.0"
