id = "pollinations-mcp"
name = "Pollinations MCP"
version = "1.0.10"
schema_version = 1
authors = ["Davide Ladisa <info@davideladisa.it>"]
description = "Pollinations MCP is an extension for integrating Pollinations AI into Zed."
repository = "https://github.com/FrancoStino/pollinations-mcp"

[context_servers.pollinations]
name = "Pollinations MCP"
